### ISSUE TITLE
Arms detatch from body.

### ISSUE THREAD

**Issue by CommanderSlav** [FeeeeK/LCAmmoCheck#4]
After very short troubleshooting, it seems this mod loses your arms to the floor when it is paired with LethalEmotesAPI. I do not know who is to blame necessarily, besides your arms going into the floor. I suspect it is the API. Just notating here so you know.

This is on LCAmmoCheck 1.1.1 
Lethal company V49
LethalEmotesAPI 1.2.13

Edit: After further troubleshooting WITHOUT the emote mod 
It still occurs - It seems with the emote mod, I was able to reproduce immediately
Without it, I was able to get in 2 moons and while reloading, my arms sunk into the floor 

Also, I should mention, anything in your hands, besides the shotgun, will also sink into the floor.

**Comment by axd1x8a** [comment]
Yes, this was already reported in #2, there's nothing I can do about it for now, sorry, try standing up and check your ammo again, it only happens when you are crouching. 
Also note that my mod is not compatible with More Emotes (#3) and probably won't be until the author of this mod makes it more compatible with `AnimatorOverrideController`, that's known problem with it, global mods like AdvacedCompany suffers from same problems.
